### ISSUE TITLE
Cannot pip install pysmps

### ISSUE THREAD

**Issue by Schedulaar** [jmaerte/pysmps#4]
Running `pip3 install pysmps` yields the following error for me:
```
Collecting pysmps
  Using cached https://files.pythonhosted.org/packages/18/e7/9334c53ef8487377c7efbbee823d661f9617277d0d545fdc8c13c315e472/pysmps-1.5.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-kl7a9R/pysmps/setup.py", line 3, in <module>
        with open('requirements.txt', "r") as reader:
    IOError: [Errno 2] No such file or directory: 'requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kl7a9R/pysmps/
```
Did I do something wrong or is this an error on your side?

**Comment by jmaerte** [comment]
I reproduced the error on my side.
The behaviour comes from a corrupted zip-file when I commited the last version (1.5.3) on pypi.

Thanks for drawing my attention towards this.

The issue should be fixed with the latest commit (version 1.5.4) to pypi. On my side `pip install pysmps` works just fine again. Thus closing this issue.
